version: "3.7"
services:
  service-api:
    restart: always
    image:  zhasst/api-v1-ets:latest
    network_mode: bridge
    volumes:
      - "/var/log/app:/var/log/app"
    ports:
      - "8082:8080"
    container_name: container-api
    environment:
      - SPRING_PROFILES_ACTIVE=prod
