proxy:
  host: proxy.tele2.kz
  port: 9090
spring:
  application:
    name: ets-api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: WZcjCH6f
    url: jdbc:mysql://localhost:3306/db_kc?useSSL=false&serverTimezone=UTC
    username: kc
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
